ERROR_FILE_PATH = "/log.txt"

I2C_FREQUENCY_HZ = 400000
PWM_FREQUENCY_HZ = 50

SERVO_MOTOR_WAIT_TIME_SEC = 0.5
ULTRASONIC_SENSOR_MEASURE_INTERVAL_SEC = 0.1
ULTRASONIC_SENSOR_MAX_TRY = 1000
ALLOW_TEMPERATURE_MAX = 40
